name: Qt 6 Windows CI/CD (Optimized)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

env:
  BUILD_TYPE: Release
  QT_VERSION: 6.7.2
  ARTIFACT_NAME: ncm2mp3-setup
  NSIS_SCRIPT_NAME: install.nsi

jobs:
  build-and-release:
    name: Build and Release on Windows
    runs-on: windows-2019
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/Qt/'
        install-deps: 'true'

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -A x64 -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Package
      working-directory: ${{github.workspace}}/build/${{env.BUILD_TYPE}}
      shell: pwsh
      run: |
        Write-Output "Qt6_DIR: $env:Qt6_DIR"
        
        $windeployqtPath = Get-ChildItem -Path $env:Qt6_DIR -Recurse -Filter "windeployqt.exe" | Select-Object -First 1 -ExpandProperty FullName
        
        if ($windeployqtPath) {
          Write-Output "windeployqt found at: $windeployqtPath"
          & $windeployqtPath . --release --compiler-runtime
          if ($LASTEXITCODE -ne 0) {
            Write-Error "windeployqt failed with exit code $LASTEXITCODE"
            exit 1
          }
        } else {
          Write-Error "windeployqt.exe not found in Qt directory"
          Get-ChildItem -Path $env:Qt6_DIR -Recurse | Where-Object { $_.Name -like "*deploy*" } | ForEach-Object { Write-Output $_.FullName }
          exit 1
        }

    - name: Install NSIS
      uses: joncloud/makensis-action@v3.7

    - name: Prepare for NSIS
      shell: pwsh
      run: |
        $buildDir = "${{github.workspace}}/build/${{env.BUILD_TYPE}}"
        Copy-Item "${{github.workspace}}/${{ env.NSIS_SCRIPT_NAME }}" -Destination $buildDir
        Write-Output "Contents of build directory:"
        Get-ChildItem -Path $buildDir -Recurse

    - name: Create Installer
      shell: pwsh
      run: |
        $buildDir = "${{github.workspace}}/build/${{env.BUILD_TYPE}}"
        Set-Location $buildDir
        Write-Output "Current directory: $buildDir"
        Write-Output "Current directory contents:"
        Get-ChildItem -Recurse
        
        # 检查 ncm2mp3.exe 是否存在
        if (Test-Path "ncm2mp3.exe") {
            Write-Output "ncm2mp3.exe found in current directory"
        } else {
            Write-Error "ncm2mp3.exe not found in current directory"
            exit 1
        }
        
        $nsisPath = "C:\Program Files (x86)\NSIS\makensis.exe"
        Write-Output "Running NSIS with command: $nsisPath /V3 ${{ env.NSIS_SCRIPT_NAME }}"
        & $nsisPath /V3 ${{ env.NSIS_SCRIPT_NAME }}
        if ($LASTEXITCODE -ne 0) {
          Write-Error "makensis failed with exit code $LASTEXITCODE"
          exit 1
        }
        
        if (Test-Path "${{ env.ARTIFACT_NAME }}.exe") {
          Move-Item "${{ env.ARTIFACT_NAME }}.exe" -Destination ${{github.workspace}}
          Write-Output "Installer created and moved to workspace"
        } else {
          Write-Error "Installer not created"
          exit 1
        }

    - name: Check Installer
      shell: pwsh
      run: |
        $installerPath = ".\ncm2mp3-setup.exe"
        if (Test-Path $installerPath) {
          Write-Output "Installer created successfully at $installerPath"
        } else {
          Write-Error "Installer not found at $installerPath"
          Get-ChildItem -Recurse
          exit 1
        }

    - name: Generate release tag
      id: tag
      shell: pwsh
      run: |
        $timestamp = Get-Date -Format "yyyy.MM.dd_HH-mm"
        $releaseTag = "UserBuild_$timestamp"
        echo "release_tag=$releaseTag" >> $env:GITHUB_OUTPUT
        echo "Generated release tag: $releaseTag"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        release_name: Release ${{ steps.tag.outputs.release_tag }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ncm2mp3-setup.exe
        asset_name: ncm2mp3-setup.exe
        asset_content_type: application/vnd.microsoft.portable-executable